// Free-text category terms -> OSM tag pairs. Kept separate from CATEGORY_TAGS
// so the existing 8-slug preset validation (KNOWN_CATEGORIES / @IsIn) is
// untouched. Matching is case-insensitive exact match on the trimmed term;
// a few synonym keys point at the same tag pairs rather than a stemming
// layer -- simplest correct v1.
export const CUSTOM_CATEGORY_TAGS: Record<string, [string, string][]> = {
  bakery: [['shop', 'bakery']],
  restaurant: [['amenity', 'restaurant']],
  cafe: [['amenity', 'cafe']],
  coffee: [['amenity', 'cafe']],
  pharmacy: [['amenity', 'pharmacy']],
  'hardware store': [['shop', 'hardware']],
  hardware: [['shop', 'hardware']],
  grocery: [['shop', 'supermarket'], ['shop', 'convenience']],
  supermarket: [['shop', 'supermarket']],
  convenience: [['shop', 'convenience']],
  hairdresser: [['shop', 'hairdresser']],
  'hair salon': [['shop', 'hairdresser']],
  barber: [['shop', 'hairdresser']],
  gym: [['leisure', 'fitness_centre']],
  fitness: [['leisure', 'fitness_centre']],
  dentist: [['amenity', 'dentist']],
  doctor: [['amenity', 'doctors']],
  clinic: [['amenity', 'doctors']],
  mechanic: [['shop', 'car_repair']],
  'auto repair': [['shop', 'car_repair']],
  bar: [['amenity', 'bar']],
  pub: [['amenity', 'pub']],
  hotel: [['tourism', 'hotel']],
  bookstore: [['shop', 'books']],
  books: [['shop', 'books']],
  'clothing store': [['shop', 'clothes']],
  clothes: [['shop', 'clothes']],
  bank: [['amenity', 'bank']],
  laundry: [['shop', 'laundry']],
  'dry cleaner': [['shop', 'laundry']],
  florist: [['shop', 'florist']],
  flowers: [['shop', 'florist']],
  'pet store': [['shop', 'pet']],
  'pet shop': [['shop', 'pet']],
  jeweler: [['shop', 'jewelry']],
  jewelry: [['shop', 'jewelry']],
  optician: [['shop', 'optician']],
  furniture: [['shop', 'furniture']],
  electronics: [['shop', 'electronics']],
  butcher: [['shop', 'butcher']],
  bicycle: [['shop', 'bicycle']],
  library: [['amenity', 'library']],
  veterinary: [['amenity', 'veterinary']],
  vet: [['amenity', 'veterinary']],
};
